#!/usr/bin/env node

import { Command } from 'commander';
import chalk from 'chalk';
import ora from 'ora';
import { fetchUserProfile } from './api/github.js';
import { getCached, setCache, clearCache } from './api/cache.js';
import { renderHeader, renderDivider } from './ui/header.js';
import { renderProfile, renderStats } from './ui/stats.js';
import { renderLanguages } from './ui/languages.js';
import { renderHeatmap, renderCommitPatterns } from './ui/heatmap.js';
import { renderTopRepos } from './ui/repos.js';
import { renderScore, renderStreak } from './ui/score.js';
import { renderComparison } from './ui/compare.js';
import { renderMinimal } from './ui/minimal.js';
import { generateThreeJSExport } from './ui/export.js';
import type { UserProfile } from './types/index.js';

const program = new Command();

program
  .name('gitpulse')
  .description('Generate beautiful developer profile report cards from GitHub')
  .version('1.0.0')
  .argument('[username]', 'GitHub username to analyze')
  .option('-t, --token <token>', 'GitHub personal access token for higher rate limits')
  .option('-j, --json', 'Output raw JSON data')
  .option('-m, --minimal', 'Compact minimal output')
  .option('-e, --export', 'Export Three.js-compatible scene data as JSON')
  .option('-c, --compare <username>', 'Compare with another user')
  .option('--no-cache', 'Bypass cache and fetch fresh data')
  .option('--clear-cache', 'Clear cached data')
  .action(async (username: string | undefined, options) => {
    try {
      // Handle clear-cache
      if (options.clearCache) {
        const count = clearCache(username);
        console.log(chalk.green(`✓ Cleared ${count} cached ${count === 1 ? 'profile' : 'profiles'}`));
        return;
      }

      if (!username) {
        program.help();
        return;
      }

      // Fetch or load profile
      const profile = await loadProfile(username, options);

      // Compare mode
      if (options.compare) {
        const otherProfile = await loadProfile(options.compare, options);
        if (options.json) {
          console.log(JSON.stringify({ a: profile, b: otherProfile }, null, 2));
        } else {
          console.log(renderHeader());
          console.log(renderComparison(profile, otherProfile));
          console.log('\n' + renderDivider());
        }
        return;
      }

      // JSON output
      if (options.json) {
        console.log(JSON.stringify(profile, null, 2));
        return;
      }

      // Three.js export
      if (options.export) {
        const sceneData = generateThreeJSExport(profile);
        console.log(JSON.stringify(sceneData, null, 2));
        return;
      }

      // Minimal output
      if (options.minimal) {
        console.log(renderMinimal(profile));
        return;
      }

      // Full report card
      renderFullReport(profile);
    } catch (error) {
      if (error instanceof Error) {
        console.error(chalk.red(`\n  ✖ Error: ${error.message}\n`));
      } else {
        console.error(chalk.red('\n  ✖ An unexpected error occurred\n'));
      }
      process.exit(1);
    }
  });

async function loadProfile(username: string, options: { token?: string; cache?: boolean }): Promise<UserProfile> {
  // Check cache first
  if (options.cache !== false) {
    const cached = getCached(username);
    if (cached) {
      return cached;
    }
  }

  const spinner = ora({
    text: chalk.dim(`Scanning ${chalk.white(username)}'s GitHub profile...`),
    spinner: 'dots12',
  }).start();

  try {
    const profile = await fetchUserProfile(username, { token: options.token });
    spinner.succeed(chalk.dim(`Profile loaded for ${chalk.white(username)}`));

    // Cache the result
    setCache(username, profile);

    return profile;
  } catch (error) {
    spinner.fail(chalk.red(`Failed to fetch profile for ${username}`));
    throw error;
  }
}

function renderFullReport(profile: UserProfile): void {
  console.log(renderHeader());
  console.log(renderProfile(profile));
  console.log(renderStats(profile));
  console.log(renderLanguages(profile.languages));
  console.log(renderTopRepos(profile.repos));
  console.log(renderHeatmap(profile.contributions));
  console.log(renderCommitPatterns(profile.commitPattern));
  console.log(renderStreak(profile.streak));
  console.log(renderScore(profile.score));
  console.log('\n' + renderDivider());
  console.log(chalk.dim(`  Generated by gitpulse • ${new Date().toLocaleDateString()}`));
  console.log('');
}

program.parse();
